### ISSUE TITLE
master not compiling

### ISSUE THREAD

**Issue by georgmittendorfer** [peercoin/peercoin#168] opened 2017-09-10 16:53 UTC
Hi, I just wanted to let you know that I get compile errors when trying to build master (on debian). This is probably related to the openssl version and already fixed (by https://github.com/peercoin/peercoin/pull/153?) in develop as the develop branch builds without problems.

Error log:

```
src/bignum.h:51:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from src/bignum.h:10,
                 from src/main.h:9,
                 from src/wallet.h:9,
                 from src/init.h:8,
                 from src/qt/bitcoin.cpp:11:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from src/main.h:9:0,
                 from src/wallet.h:9,
                 from src/init.h:8,
                 from src/qt/bitcoin.cpp:11:
src/bignum.h: In constructor ‘CBigNum::CBigNum()’:
src/bignum.h:56:21: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
                     ^
src/bignum.h: In copy constructor ‘CBigNum::CBigNum(const CBigNum&)’:
src/bignum.h:61:21: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
                     ^
src/bignum.h:62:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
src/bignum.h:64:31: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
             BN_clear_free(this);
                               ^
src/bignum.h: In member function ‘CBigNum& CBigNum::operator=(const CBigNum&)’:
src/bignum.h:71:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
src/bignum.h: In destructor ‘CBigNum::~CBigNum()’:
src/bignum.h:78:27: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
         BN_clear_free(this);
                           ^
src/bignum.h: In constructor ‘CBigNum::CBigNum(signed char)’:
src/bignum.h:82:47: error: ‘BN_init’ was not declared in this scope
     CBigNum(signed char n)      { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                               ^
src/bignum.h: In constructor ‘CBigNum::CBigNum(short int)’:
src/bignum.h:83:47: error: ‘BN_init’ was not declared in this scope
     CBigNum(short n)            { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                               ^
src/bignum.h: In constructor ‘CBigNum::CBigNum(int)’:
src/bignum.h:84:47: error: ‘BN_init’ was not declared in this scope
     CBigNum(int n)              { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                               ^
src/bignum.h: In constructor ‘CBigNum::CBigNum(long int)’:
src/bignum.h:85:47: error: ‘BN_init’ was not declared in this scope
     CBigNum(long n)             { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                               ^
src/bignum.h: In constructor ‘CBigNum::CBigNum(int64)’:
src/bignum.h:86:47: error: ‘BN_init’ was not declared in this scope
     CBigNum(int64 n)            { BN_init(this); setint64(n); }
                                               ^
```

... and so on.

**Comment by hrobeers** [comment] 2017-10-08 12:34
This is caused by the backwards incompatible changes in OpenSSL v1.1
You should compile against OpenSSL v1.0, most linux distros have instructions for that because more applications suffer this upgrade.

Or you can backport this commit from develop: https://github.com/peercoin/peercoin/commit/5b09830e5de0f5105534e69dbf4acffb3255869b

**Comment by hrobeers** [comment] 2017-11-05 07:35
Since master is updated to v0.6 this should be fixed.

**Closed by hrobeers** 2017-11-05 07:35 UTC
